const coreKeywords = [
  'ragdoll kittens',
  'ragdoll cats Arizona',
  'TICA ragdoll breeder',
  'ragdoll adoption',
  'azure sky ragdolls',
  'ragdoll cattery',
  'purebred ragdoll kittens',
  'family raised ragdoll cats',
]

const kamloopsAdoptionKeywords = [
  'ragdoll kittens for adoption kamloops',
  'ragdoll cats for adoption kamloops',
  'adopt a ragdoll kitten kamloops bc',
  'ragdoll kitten rescue kamloops',
  'ragdoll cat rescue kamloops bc',
  'kamloops ragdoll cat adoption',
  'ragdoll kittens kamloops area',
  'purebred ragdoll kittens kamloops',
  'tica registered ragdoll kittens kamloops',
  'azureskyragdolls.com',
  'ragdoll kitten application kamloops',
  'ragdoll kittens ready to go kamloops',
  'ragdoll kittens available kamloops today',
  'blue point ragdoll kittens kamloops',
  'seal point ragdoll kittens kamloops',
  'ragdoll kittens rehoming kamloops',
  'ragdoll kittens needing homes kamloops',
  'retired ragdoll cat for adoption kamloops',
  'adult ragdoll cat adoption kamloops',
  'ragdoll mix kittens for adoption kamloops',
  'affordable ragdoll kittens kamloops bc',
  'ragdoll kittens under 1000 kamloops',
  'ragdoll kitten waitlist kamloops',
  'local ragdoll cattery kamloops',
  'indoor ragdoll cats for adoption kamloops',
  'family-friendly ragdoll kittens kamloops',
  'ragdoll kittens good with kids kamloops',
  'ragdoll kittens for adoption merritt bc',
  'ragdoll kittens for adoption clearwater bc',
  'ragdoll kittens for adoption salmon arm',
  'ragdoll kittens for adoption vernon bc',
  'ragdoll kittens for adoption chase bc',
  'ragdoll kittens for adoption sicamous bc',
  'ragdoll kittens for adoption armstrong bc',
  'ragdoll kittens for adoption enderby bc',
  'ragdoll kittens for adoption lumby bc',
  'ragdoll kittens for adoption kelowna bc',
  'ragdoll cat rescue okanagan',
  'ragdoll kittens north okanagan shuswap',
  'ragdoll kittens thompson nicola',
  'ragdoll breeder near kamloops',
  'ragdoll kittens near kamloops bc',
  'ragdoll kittens near me kamloops',
  'ragdoll cats near me kamloops',
  'ragdoll kittens near me british columbia',
  'ragdoll cat adoption near me bc',
  'ragdoll kittens for adoption bc canada',
  'ragdoll kittens for adoption interior bc',
  'ragdoll cat rescue british columbia',
  'ragdoll kittens for rehoming bc',
  'adopt a ragdoll kitten in bc',
  'ragdoll kittens for sale bc',
  'ragdoll kittens bc spca',
  'ragdoll kittens petfinder kamloops',
  'ragdoll kitten rescue kamloops bc',
  'rescue ragdoll cat kamloops',
  'ragdoll cat shelter kamloops',
  'ragdoll kittens bc spca kamloops',
  'ragdoll cats kamloops humane society',
  'ragdoll kittens better beginnings kitten rescue',
  'ragdoll kittens local cat rescue kamloops',
  'foster to adopt ragdoll kamloops',
  'ragdoll cats needing foster homes kamloops',
  'special needs ragdoll cats kamloops',
  'bonded pair ragdoll cats for adoption kamloops',
  'Facebook',
  'BC SPCA',
  'Better Beginnings Kitten Rescue',
  'Petfinder',
  'how to adopt a ragdoll cat in kamloops',
  'where to adopt ragdoll kittens in kamloops',
  'are ragdoll cats good with children',
  'are ragdoll cats hypoallergenic',
  'ragdoll cat temperament with dogs',
  'do ragdoll cats shed a lot',
  'ragdoll cat personality vs siamese',
  'what to know before adopting a ragdoll cat',
  'ragdoll kitten first-time owner tips',
  'indoor vs outdoor for ragdoll cats',
  'are ragdoll cats healthy breed',
  'common health issues in ragdoll cats',
  'how long do ragdoll cats live',
  'best litter for ragdoll cats',
  'best food for ragdoll kittens',
  'ragdoll kitten price kamloops',
  'ragdoll cat adoption fee kamloops',
  'how much do ragdoll kittens cost in bc',
  'ragdoll kitten price range kamloops',
  'ragdoll kittens payment plan kamloops',
  'ragdoll kitten deposit kamloops',
  'ragdoll adoption contract kamloops',
  'ragdoll kitten health guarantee kamloops',
  'spay neuter included ragdoll kitten kamloops',
  'vaccinated ragdoll kittens kamloops',
  'microchipped ragdoll kittens kamloops',
  'blue point ragdoll kittens',
  'seal point ragdoll kittens',
  'lilac ragdoll kittens',
  'mitted ragdoll kittens',
  'bicolor ragdoll kittens',
  'flame point ragdoll kittens',
  'ragdoll kittens under 12 weeks',
  'older ragdoll cat for adoption',
  'senior ragdoll cat adoption',
  'ragdoll kittens ready by christmas kamloops',
  'ragdoll kittens spring litters kamloops',
  'ragdoll cats for apartments kamloops',
  'ragdoll cats for families kamloops',
  'ragdoll cats good with other cats kamloops',
  'calm cat breed for kids kamloops ragdoll',
  'cuddly cat breed kamloops ragdoll',
  'low energy indoor cat ragdoll',
]

const siteMetadata = {
  siteName: 'Azure Sky Ragdolls',
  siteUrl: 'https://www.azureskyragdolls.com',
  title: 'Azure Sky Ragdolls | TICA Registered Ragdoll Kittens in Arizona',
  description:
    'Azure Sky Ragdolls is a TICA-registered boutique cattery in Arizona offering healthy, affectionate Ragdoll kittens along with detailed care guidance, transparent purchasing steps, and regular litter updates.',
  keywords: [...coreKeywords, ...kamloopsAdoptionKeywords],
  contactEmail: 'Meg@azureskyragdolls.com',
  organizationType: 'Organization',
  socialImage: '/favicon/android-chrome-512x512.png',
  locale: 'en_US',
}

export default siteMetadata
export { coreKeywords, kamloopsAdoptionKeywords }
